plugins {
    id 'java-library'
}

test {
    useJUnitPlatform()
}

dependencies {
    api 'com.github.crykn:kryonet:2.22.8'
    implementation 'org.ow2.asm:asm:9.5'
    implementation 'org.ow2.asm:asm-commons:9.5'

    // JUnit for testing
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.9.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.9.2'
}
